name: ktlint
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
          architecture: 'x64'
      - name: Cache danger
        uses: actions/cache@v1
        env:
          cache-name: cache-gem-danger
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install danger
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Cache gradlew
        uses: actions/cache@v1
        env:
          cache-name: cache-gradle-gradlew
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            ${{ runner.os }}-
      - name: Run ktlintCheck
        run: ./gradlew ktlintCheck
      - name: Run danger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bundle exec danger